// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog;

/** Abstract Visitor */

public class AbstractVisitor<R,A> implements AllVisitor<R,A> {
    /* ProgramDef */
    public R visit(cp2025.datalog.Absyn.Program p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.ProgramDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* ConstantsDef */
    public R visit(cp2025.datalog.Absyn.Constants p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.ConstantsDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* RulesDef */
    public R visit(cp2025.datalog.Absyn.Rules p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.RulesDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* RuleDef */
    public R visit(cp2025.datalog.Absyn.Rule p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.RuleDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* AtomDef */
    public R visit(cp2025.datalog.Absyn.Atom p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.AtomDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Element */
    public R visit(cp2025.datalog.Absyn.ConstElement p, A arg) { return visitDefault(p, arg); }
    public R visit(cp2025.datalog.Absyn.VarElement p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.Element p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* PredicateDef */
    public R visit(cp2025.datalog.Absyn.LPredicate p, A arg) { return visitDefault(p, arg); }
    public R visit(cp2025.datalog.Absyn.LSPredicate p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.PredicateDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* QueriesDef */
    public R visit(cp2025.datalog.Absyn.Queries p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.QueriesDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* StatementDef */
    public R visit(cp2025.datalog.Absyn.Statement p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(cp2025.datalog.Absyn.StatementDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }

}
