// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog;

/** All Visitor */

public interface AllVisitor<R,A> extends
  cp2025.datalog.Absyn.ProgramDef.Visitor<R,A>,
  cp2025.datalog.Absyn.ConstantsDef.Visitor<R,A>,
  cp2025.datalog.Absyn.RulesDef.Visitor<R,A>,
  cp2025.datalog.Absyn.RuleDef.Visitor<R,A>,
  cp2025.datalog.Absyn.AtomDef.Visitor<R,A>,
  cp2025.datalog.Absyn.Element.Visitor<R,A>,
  cp2025.datalog.Absyn.PredicateDef.Visitor<R,A>,
  cp2025.datalog.Absyn.QueriesDef.Visitor<R,A>,
  cp2025.datalog.Absyn.StatementDef.Visitor<R,A>
{}
