// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog;
/** Composition Visitor
*/

public class ComposVisitor<A> implements
  cp2025.datalog.Absyn.ProgramDef.Visitor<cp2025.datalog.Absyn.ProgramDef,A>,
  cp2025.datalog.Absyn.ConstantsDef.Visitor<cp2025.datalog.Absyn.ConstantsDef,A>,
  cp2025.datalog.Absyn.RulesDef.Visitor<cp2025.datalog.Absyn.RulesDef,A>,
  cp2025.datalog.Absyn.RuleDef.Visitor<cp2025.datalog.Absyn.RuleDef,A>,
  cp2025.datalog.Absyn.AtomDef.Visitor<cp2025.datalog.Absyn.AtomDef,A>,
  cp2025.datalog.Absyn.Element.Visitor<cp2025.datalog.Absyn.Element,A>,
  cp2025.datalog.Absyn.PredicateDef.Visitor<cp2025.datalog.Absyn.PredicateDef,A>,
  cp2025.datalog.Absyn.QueriesDef.Visitor<cp2025.datalog.Absyn.QueriesDef,A>,
  cp2025.datalog.Absyn.StatementDef.Visitor<cp2025.datalog.Absyn.StatementDef,A>
{
    /* ProgramDef */
    public cp2025.datalog.Absyn.ProgramDef visit(cp2025.datalog.Absyn.Program p, A arg)
    {
      cp2025.datalog.Absyn.ConstantsDef constantsdef_ = p.constantsdef_.accept(this, arg);
      cp2025.datalog.Absyn.RulesDef rulesdef_ = p.rulesdef_.accept(this, arg);
      cp2025.datalog.Absyn.QueriesDef queriesdef_ = p.queriesdef_.accept(this, arg);
      return new cp2025.datalog.Absyn.Program(constantsdef_, rulesdef_, queriesdef_);
    }

    /* ConstantsDef */
    public cp2025.datalog.Absyn.ConstantsDef visit(cp2025.datalog.Absyn.Constants p, A arg)
    {
      cp2025.datalog.Absyn.ListLIdent listlident_ = p.listlident_;
      return new cp2025.datalog.Absyn.Constants(listlident_);
    }

    /* RulesDef */
    public cp2025.datalog.Absyn.RulesDef visit(cp2025.datalog.Absyn.Rules p, A arg)
    {
      cp2025.datalog.Absyn.ListRuleDef listruledef_ = new cp2025.datalog.Absyn.ListRuleDef();
      for (cp2025.datalog.Absyn.RuleDef x : p.listruledef_)
      {
        listruledef_.add(x.accept(this,arg));
      }
      return new cp2025.datalog.Absyn.Rules(listruledef_);
    }

    /* RuleDef */
    public cp2025.datalog.Absyn.RuleDef visit(cp2025.datalog.Absyn.Rule p, A arg)
    {
      cp2025.datalog.Absyn.AtomDef atomdef_ = p.atomdef_.accept(this, arg);
      cp2025.datalog.Absyn.ListAtomDef listatomdef_ = new cp2025.datalog.Absyn.ListAtomDef();
      for (cp2025.datalog.Absyn.AtomDef x : p.listatomdef_)
      {
        listatomdef_.add(x.accept(this,arg));
      }
      return new cp2025.datalog.Absyn.Rule(atomdef_, listatomdef_);
    }

    /* AtomDef */
    public cp2025.datalog.Absyn.AtomDef visit(cp2025.datalog.Absyn.Atom p, A arg)
    {
      cp2025.datalog.Absyn.PredicateDef predicatedef_ = p.predicatedef_.accept(this, arg);
      cp2025.datalog.Absyn.ListElement listelement_ = new cp2025.datalog.Absyn.ListElement();
      for (cp2025.datalog.Absyn.Element x : p.listelement_)
      {
        listelement_.add(x.accept(this,arg));
      }
      return new cp2025.datalog.Absyn.Atom(predicatedef_, listelement_);
    }

    /* Element */
    public cp2025.datalog.Absyn.Element visit(cp2025.datalog.Absyn.ConstElement p, A arg)
    {
      String lident_ = p.lident_;
      return new cp2025.datalog.Absyn.ConstElement(lident_);
    }
    public cp2025.datalog.Absyn.Element visit(cp2025.datalog.Absyn.VarElement p, A arg)
    {
      String uident_ = p.uident_;
      return new cp2025.datalog.Absyn.VarElement(uident_);
    }

    /* PredicateDef */
    public cp2025.datalog.Absyn.PredicateDef visit(cp2025.datalog.Absyn.LPredicate p, A arg)
    {
      String lident_ = p.lident_;
      return new cp2025.datalog.Absyn.LPredicate(lident_);
    }
    public cp2025.datalog.Absyn.PredicateDef visit(cp2025.datalog.Absyn.LSPredicate p, A arg)
    {
      String lsident_ = p.lsident_;
      return new cp2025.datalog.Absyn.LSPredicate(lsident_);
    }

    /* QueriesDef */
    public cp2025.datalog.Absyn.QueriesDef visit(cp2025.datalog.Absyn.Queries p, A arg)
    {
      cp2025.datalog.Absyn.ListStatementDef liststatementdef_ = new cp2025.datalog.Absyn.ListStatementDef();
      for (cp2025.datalog.Absyn.StatementDef x : p.liststatementdef_)
      {
        liststatementdef_.add(x.accept(this,arg));
      }
      return new cp2025.datalog.Absyn.Queries(liststatementdef_);
    }

    /* StatementDef */
    public cp2025.datalog.Absyn.StatementDef visit(cp2025.datalog.Absyn.Statement p, A arg)
    {
      cp2025.datalog.Absyn.PredicateDef predicatedef_ = p.predicatedef_.accept(this, arg);
      cp2025.datalog.Absyn.ListLIdent listlident_ = p.listlident_;
      return new cp2025.datalog.Absyn.Statement(predicatedef_, listlident_);
    }
}
