// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog;

/** Fold Visitor */
public abstract class FoldVisitor<R,A> implements AllVisitor<R,A> {
    public abstract R leaf(A arg);
    public abstract R combine(R x, R y, A arg);

/* ProgramDef */
    public R visit(cp2025.datalog.Absyn.Program p, A arg) {
      R r = leaf(arg);
      r = combine(p.constantsdef_.accept(this, arg), r, arg);
      r = combine(p.rulesdef_.accept(this, arg), r, arg);
      r = combine(p.queriesdef_.accept(this, arg), r, arg);
      return r;
    }

/* ConstantsDef */
    public R visit(cp2025.datalog.Absyn.Constants p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* RulesDef */
    public R visit(cp2025.datalog.Absyn.Rules p, A arg) {
      R r = leaf(arg);
      for (cp2025.datalog.Absyn.RuleDef x : p.listruledef_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* RuleDef */
    public R visit(cp2025.datalog.Absyn.Rule p, A arg) {
      R r = leaf(arg);
      r = combine(p.atomdef_.accept(this, arg), r, arg);
      for (cp2025.datalog.Absyn.AtomDef x : p.listatomdef_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* AtomDef */
    public R visit(cp2025.datalog.Absyn.Atom p, A arg) {
      R r = leaf(arg);
      r = combine(p.predicatedef_.accept(this, arg), r, arg);
      for (cp2025.datalog.Absyn.Element x : p.listelement_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Element */
    public R visit(cp2025.datalog.Absyn.ConstElement p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(cp2025.datalog.Absyn.VarElement p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* PredicateDef */
    public R visit(cp2025.datalog.Absyn.LPredicate p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(cp2025.datalog.Absyn.LSPredicate p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* QueriesDef */
    public R visit(cp2025.datalog.Absyn.Queries p, A arg) {
      R r = leaf(arg);
      for (cp2025.datalog.Absyn.StatementDef x : p.liststatementdef_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* StatementDef */
    public R visit(cp2025.datalog.Absyn.Statement p, A arg) {
      R r = leaf(arg);
      r = combine(p.predicatedef_.accept(this, arg), r, arg);
      return r;
    }


}
