// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog;

@SuppressWarnings("unused")
public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(cp2025.datalog.Absyn.ProgramDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.ProgramDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.ConstantsDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.ConstantsDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.ListLIdent foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.ListLIdent foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.RulesDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.RulesDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.ListRuleDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.ListRuleDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.RuleDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.RuleDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.ListAtomDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.ListAtomDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.AtomDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.AtomDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.ListElement foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.ListElement foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.Element foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.Element foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.PredicateDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.PredicateDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.QueriesDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.QueriesDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.ListStatementDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.ListStatementDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(cp2025.datalog.Absyn.StatementDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(cp2025.datalog.Absyn.StatementDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(cp2025.datalog.Absyn.ProgramDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.Program)
    {
       cp2025.datalog.Absyn.Program _program = (cp2025.datalog.Absyn.Program) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_program.constantsdef_, 0);
       pp(_program.rulesdef_, 0);
       pp(_program.queriesdef_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.ConstantsDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.Constants)
    {
       cp2025.datalog.Absyn.Constants _constants = (cp2025.datalog.Absyn.Constants) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("Constants:");
       pp(_constants.listlident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.ListLIdent foo, int _i_)
  {
    ppListLIdent(foo.iterator(), _i_);
  }

  private static void ppListLIdent(java.util.Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListLIdent(it, _i_);
      }
    }
  }


  private static void pp(cp2025.datalog.Absyn.RulesDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.Rules)
    {
       cp2025.datalog.Absyn.Rules _rules = (cp2025.datalog.Absyn.Rules) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("Rules:");
       pp(_rules.listruledef_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.ListRuleDef foo, int _i_)
  {
    ppListRuleDef(foo.iterator(), _i_);
  }

  private static void ppListRuleDef(java.util.Iterator<cp2025.datalog.Absyn.RuleDef> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      cp2025.datalog.Absyn.RuleDef el = it.next();
      pp(el, _i_); render("."); ppListRuleDef(it, _i_);
    }
  }


  private static void pp(cp2025.datalog.Absyn.RuleDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.Rule)
    {
       cp2025.datalog.Absyn.Rule _rule = (cp2025.datalog.Absyn.Rule) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_rule.atomdef_, 0);
       render(":-");
       pp(_rule.listatomdef_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.ListAtomDef foo, int _i_)
  {
    ppListAtomDef(foo.iterator(), _i_);
  }

  private static void ppListAtomDef(java.util.Iterator<cp2025.datalog.Absyn.AtomDef> it, int _i_)
  {
    if (it.hasNext())
    {
      cp2025.datalog.Absyn.AtomDef el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListAtomDef(it, _i_);
      }
    }
  }


  private static void pp(cp2025.datalog.Absyn.AtomDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.Atom)
    {
       cp2025.datalog.Absyn.Atom _atom = (cp2025.datalog.Absyn.Atom) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_atom.predicatedef_, 0);
       render("(");
       pp(_atom.listelement_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.ListElement foo, int _i_)
  {
    ppListElement(foo.iterator(), _i_);
  }

  private static void ppListElement(java.util.Iterator<cp2025.datalog.Absyn.Element> it, int _i_)
  {
    if (it.hasNext())
    {
      cp2025.datalog.Absyn.Element el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListElement(it, _i_);
      }
    }
  }


  private static void pp(cp2025.datalog.Absyn.Element foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.ConstElement)
    {
       cp2025.datalog.Absyn.ConstElement _constelement = (cp2025.datalog.Absyn.ConstElement) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_constelement.lident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof cp2025.datalog.Absyn.VarElement)
    {
       cp2025.datalog.Absyn.VarElement _varelement = (cp2025.datalog.Absyn.VarElement) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_varelement.uident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.PredicateDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.LPredicate)
    {
       cp2025.datalog.Absyn.LPredicate _lpredicate = (cp2025.datalog.Absyn.LPredicate) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_lpredicate.lident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof cp2025.datalog.Absyn.LSPredicate)
    {
       cp2025.datalog.Absyn.LSPredicate _lspredicate = (cp2025.datalog.Absyn.LSPredicate) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_lspredicate.lsident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.QueriesDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.Queries)
    {
       cp2025.datalog.Absyn.Queries _queries = (cp2025.datalog.Absyn.Queries) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("Queries:");
       pp(_queries.liststatementdef_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(cp2025.datalog.Absyn.ListStatementDef foo, int _i_)
  {
    ppListStatementDef(foo.iterator(), _i_);
  }

  private static void ppListStatementDef(java.util.Iterator<cp2025.datalog.Absyn.StatementDef> it, int _i_)
  {
    if (it.hasNext())
    {
      cp2025.datalog.Absyn.StatementDef el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListStatementDef(it, _i_);
      }
    }
  }


  private static void pp(cp2025.datalog.Absyn.StatementDef foo, int _i_)
  {
    if (foo instanceof cp2025.datalog.Absyn.Statement)
    {
       cp2025.datalog.Absyn.Statement _statement = (cp2025.datalog.Absyn.Statement) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_statement.predicatedef_, 0);
       render("(");
       pp(_statement.listlident_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(cp2025.datalog.Absyn.ProgramDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.Program)
    {
       cp2025.datalog.Absyn.Program _program = (cp2025.datalog.Absyn.Program) foo;
       render("(");
       render("Program");
       sh(_program.constantsdef_);
       sh(_program.rulesdef_);
       sh(_program.queriesdef_);
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.ConstantsDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.Constants)
    {
       cp2025.datalog.Absyn.Constants _constants = (cp2025.datalog.Absyn.Constants) foo;
       render("(");
       render("Constants");
       render("[");
       sh(_constants.listlident_);
       render("]");
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.ListLIdent foo)
  {
     for (java.util.Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(cp2025.datalog.Absyn.RulesDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.Rules)
    {
       cp2025.datalog.Absyn.Rules _rules = (cp2025.datalog.Absyn.Rules) foo;
       render("(");
       render("Rules");
       render("[");
       sh(_rules.listruledef_);
       render("]");
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.ListRuleDef foo)
  {
     for (java.util.Iterator<cp2025.datalog.Absyn.RuleDef> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(cp2025.datalog.Absyn.RuleDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.Rule)
    {
       cp2025.datalog.Absyn.Rule _rule = (cp2025.datalog.Absyn.Rule) foo;
       render("(");
       render("Rule");
       sh(_rule.atomdef_);
       render("[");
       sh(_rule.listatomdef_);
       render("]");
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.ListAtomDef foo)
  {
     for (java.util.Iterator<cp2025.datalog.Absyn.AtomDef> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(cp2025.datalog.Absyn.AtomDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.Atom)
    {
       cp2025.datalog.Absyn.Atom _atom = (cp2025.datalog.Absyn.Atom) foo;
       render("(");
       render("Atom");
       sh(_atom.predicatedef_);
       render("[");
       sh(_atom.listelement_);
       render("]");
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.ListElement foo)
  {
     for (java.util.Iterator<cp2025.datalog.Absyn.Element> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(cp2025.datalog.Absyn.Element foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.ConstElement)
    {
       cp2025.datalog.Absyn.ConstElement _constelement = (cp2025.datalog.Absyn.ConstElement) foo;
       render("(");
       render("ConstElement");
       sh(_constelement.lident_);
       render(")");
    }
    if (foo instanceof cp2025.datalog.Absyn.VarElement)
    {
       cp2025.datalog.Absyn.VarElement _varelement = (cp2025.datalog.Absyn.VarElement) foo;
       render("(");
       render("VarElement");
       sh(_varelement.uident_);
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.PredicateDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.LPredicate)
    {
       cp2025.datalog.Absyn.LPredicate _lpredicate = (cp2025.datalog.Absyn.LPredicate) foo;
       render("(");
       render("LPredicate");
       sh(_lpredicate.lident_);
       render(")");
    }
    if (foo instanceof cp2025.datalog.Absyn.LSPredicate)
    {
       cp2025.datalog.Absyn.LSPredicate _lspredicate = (cp2025.datalog.Absyn.LSPredicate) foo;
       render("(");
       render("LSPredicate");
       sh(_lspredicate.lsident_);
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.QueriesDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.Queries)
    {
       cp2025.datalog.Absyn.Queries _queries = (cp2025.datalog.Absyn.Queries) foo;
       render("(");
       render("Queries");
       render("[");
       sh(_queries.liststatementdef_);
       render("]");
       render(")");
    }
  }

  private static void sh(cp2025.datalog.Absyn.ListStatementDef foo)
  {
     for (java.util.Iterator<cp2025.datalog.Absyn.StatementDef> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(cp2025.datalog.Absyn.StatementDef foo)
  {
    if (foo instanceof cp2025.datalog.Absyn.Statement)
    {
       cp2025.datalog.Absyn.Statement _statement = (cp2025.datalog.Absyn.Statement) foo;
       render("(");
       render("Statement");
       sh(_statement.predicatedef_);
       render("[");
       sh(_statement.listlident_);
       render("]");
       render(")");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + escape(c.toString()) + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + escape(c.toString()) + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + escape(s) + "\""); }

  public static String escape(String s) {
    if (s == null) return null;
    return s.replace("\\", "\\\\")
            .replace("\t", "\\t")
            .replace("\b", "\\b")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\f", "\\f")
            .replace("\"", "\\\"");
  }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

