// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class Atom  extends AtomDef {
  public final PredicateDef predicatedef_;
  public final ListElement listelement_;
  public Atom(PredicateDef p1, ListElement p2) { predicatedef_ = p1; listelement_ = p2; }

  public <R,A> R accept(cp2025.datalog.Absyn.AtomDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.Atom) {
      cp2025.datalog.Absyn.Atom x = (cp2025.datalog.Absyn.Atom)o;
      return this.predicatedef_.equals(x.predicatedef_) && this.listelement_.equals(x.listelement_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.predicatedef_.hashCode())+this.listelement_.hashCode();
  }


}
