// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class ConstElement  extends Element {
  public final String lident_;
  public ConstElement(String p1) { lident_ = p1; }

  public <R,A> R accept(cp2025.datalog.Absyn.Element.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.ConstElement) {
      cp2025.datalog.Absyn.ConstElement x = (cp2025.datalog.Absyn.ConstElement)o;
      return this.lident_.equals(x.lident_);
    }
    return false;
  }

  public int hashCode() {
    return this.lident_.hashCode();
  }


}
