// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class Constants  extends ConstantsDef {
  public final ListLIdent listlident_;
  public Constants(ListLIdent p1) { listlident_ = p1; }

  public <R,A> R accept(cp2025.datalog.Absyn.ConstantsDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.Constants) {
      cp2025.datalog.Absyn.Constants x = (cp2025.datalog.Absyn.Constants)o;
      return this.listlident_.equals(x.listlident_);
    }
    return false;
  }

  public int hashCode() {
    return this.listlident_.hashCode();
  }


}
