// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public abstract class Element implements java.io.Serializable {
  public abstract <R,A> R accept(Element.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cp2025.datalog.Absyn.ConstElement p, A arg);
    public R visit(cp2025.datalog.Absyn.VarElement p, A arg);

  }

}
