// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class LPredicate  extends PredicateDef {
  public final String lident_;
  public LPredicate(String p1) { lident_ = p1; }

  public <R,A> R accept(cp2025.datalog.Absyn.PredicateDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.LPredicate) {
      cp2025.datalog.Absyn.LPredicate x = (cp2025.datalog.Absyn.LPredicate)o;
      return this.lident_.equals(x.lident_);
    }
    return false;
  }

  public int hashCode() {
    return this.lident_.hashCode();
  }


}
