// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class LSPredicate  extends PredicateDef {
  public final String lsident_;
  public LSPredicate(String p1) { lsident_ = p1; }

  public <R,A> R accept(cp2025.datalog.Absyn.PredicateDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.LSPredicate) {
      cp2025.datalog.Absyn.LSPredicate x = (cp2025.datalog.Absyn.LSPredicate)o;
      return this.lsident_.equals(x.lsident_);
    }
    return false;
  }

  public int hashCode() {
    return this.lsident_.hashCode();
  }


}
