// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public abstract class PredicateDef implements java.io.Serializable {
  public abstract <R,A> R accept(PredicateDef.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cp2025.datalog.Absyn.LPredicate p, A arg);
    public R visit(cp2025.datalog.Absyn.LSPredicate p, A arg);

  }

}
