// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class Program  extends ProgramDef {
  public final ConstantsDef constantsdef_;
  public final RulesDef rulesdef_;
  public final QueriesDef queriesdef_;
  public Program(ConstantsDef p1, RulesDef p2, QueriesDef p3) { constantsdef_ = p1; rulesdef_ = p2; queriesdef_ = p3; }

  public <R,A> R accept(cp2025.datalog.Absyn.ProgramDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.Program) {
      cp2025.datalog.Absyn.Program x = (cp2025.datalog.Absyn.Program)o;
      return this.constantsdef_.equals(x.constantsdef_) && this.rulesdef_.equals(x.rulesdef_) && this.queriesdef_.equals(x.queriesdef_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.constantsdef_.hashCode())+this.rulesdef_.hashCode())+this.queriesdef_.hashCode();
  }


}
