// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class Queries  extends QueriesDef {
  public final ListStatementDef liststatementdef_;
  public Queries(ListStatementDef p1) { liststatementdef_ = p1; }

  public <R,A> R accept(cp2025.datalog.Absyn.QueriesDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.Queries) {
      cp2025.datalog.Absyn.Queries x = (cp2025.datalog.Absyn.Queries)o;
      return this.liststatementdef_.equals(x.liststatementdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststatementdef_.hashCode();
  }


}
