// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public abstract class RulesDef implements java.io.Serializable {
  public abstract <R,A> R accept(RulesDef.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cp2025.datalog.Absyn.Rules p, A arg);

  }

}
