// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class Rules  extends RulesDef {
  public final ListRuleDef listruledef_;
  public Rules(ListRuleDef p1) { listruledef_ = p1; }

  public <R,A> R accept(cp2025.datalog.Absyn.RulesDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.Rules) {
      cp2025.datalog.Absyn.Rules x = (cp2025.datalog.Absyn.Rules)o;
      return this.listruledef_.equals(x.listruledef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listruledef_.hashCode();
  }


}
