// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class Rule  extends RuleDef {
  public final AtomDef atomdef_;
  public final ListAtomDef listatomdef_;
  public Rule(AtomDef p1, ListAtomDef p2) { atomdef_ = p1; listatomdef_ = p2; }

  public <R,A> R accept(cp2025.datalog.Absyn.RuleDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.Rule) {
      cp2025.datalog.Absyn.Rule x = (cp2025.datalog.Absyn.Rule)o;
      return this.atomdef_.equals(x.atomdef_) && this.listatomdef_.equals(x.listatomdef_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.atomdef_.hashCode())+this.listatomdef_.hashCode();
  }


}
