// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class Statement  extends StatementDef {
  public final PredicateDef predicatedef_;
  public final ListLIdent listlident_;
  public Statement(PredicateDef p1, ListLIdent p2) { predicatedef_ = p1; listlident_ = p2; }

  public <R,A> R accept(cp2025.datalog.Absyn.StatementDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.Statement) {
      cp2025.datalog.Absyn.Statement x = (cp2025.datalog.Absyn.Statement)o;
      return this.predicatedef_.equals(x.predicatedef_) && this.listlident_.equals(x.listlident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.predicatedef_.hashCode())+this.listlident_.hashCode();
  }


}
