// File generated by the BNF Converter (bnfc 2.9.6.1).

package cp2025.datalog.Absyn;

public class VarElement  extends Element {
  public final String uident_;
  public VarElement(String p1) { uident_ = p1; }

  public <R,A> R accept(cp2025.datalog.Absyn.Element.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cp2025.datalog.Absyn.VarElement) {
      cp2025.datalog.Absyn.VarElement x = (cp2025.datalog.Absyn.VarElement)o;
      return this.uident_.equals(x.uident_);
    }
    return false;
  }

  public int hashCode() {
    return this.uident_.hashCode();
  }


}
